export const GAME_SYSTEM_CONSTANTS = {
  DEFAULT_MAX_HP: 100,
  DEFAULT_TOTAL_COMMAND_SLOTS: 7,
  DEFAULT_BASE_ATTACK_DAMAGE: 10,
  DEFAULT_COUNTER_DAMAGE: 7,
  DEFAULT_THROW_DAMAGE: 14,
  MAX_CHARGE_STACK: 4,
  CHARGE_BONUS_CURVE: [0, 6, 11, 17, 24] as const,
  ASYNC_CHUNK_SIZE: 6,
  RENDER_YIELD_DELAY_MS: 16,
  DEFAULT_SLOT_COMMAND: 'MID_BLOCK' as const,
} as const;
